### ISSUE TITLE
Kernel boot stuck 

### ISSUE THREAD

**Issue by oPiZiL** [openil/openil#16]
```  
[    4.043473] mmcblk1rpmb: mmc1:0001 Q2J54A partition 3 512 KiB
[    4.053732]  mmcblk1: p1 p2
[    4.062268] fsl-asrc 2034000.asrc: failed to get spba clock
```  
[boolog.txt](https://github.com/openil/openil/files/2574448/boolog.txt)

**Comment by vladimiroltean** [comment]
```
Kernel command line: console=ttymxc0,115200 cma=320M root=/dev/mmcblk3p2 rootwait rw
```
Is your rootfs on mmcblk*3*p2 or is it a typo?

**Comment by vladimiroltean** [comment]
While technically this is the reason why your kernel boot is not proceeding further (rootwait on a non-existing root), the cause may not be a typo but instead the default U-boot env.
```
*** Warning - bad CRC, using default environment
```
The above happens most probably because your U-boot wasn't compiled with the correct defconfig so it can't find the environment (where the boot variables are held) on the boot medium. Depending on what your boot medium is, one of the following should be enabled: `CONFIG_ENV_IS_IN_MMC`, `CONFIG_ENV_IS_IN_NAND`, `CONFIG_ENV_IS_IN_FLASH`, `CONFIG_ENV_IS_IN_SPI_FLASH`, etc.

First try to do the following from u-boot:
```
=> setenv bootargs "console=ttymxc0,115200 cma=320M root=/dev/mmcblk1p2 rootwait rw"
=> boot
```
and check to see if it picked up the new root device.
If it does and it works that way, the issue as I said is the CONFIG_ENV_IS_IN_* defconfig.

**Comment by oPiZiL** [comment]
> ```
> Kernel command line: console=ttymxc0,115200 cma=320M root=/dev/mmcblk3p2 rootwait rw
> ```
> Is your rootfs on mmcblk_3_p2 or is it a typo?

rootfs is on mmcblk_3_p2

**Comment by oPiZiL** [comment]
@vladimiroltean  I can boot into another kernel with this u-boot. I just simply changed the kernel, the dtb and rootfs is the same.

**Comment by vladimiroltean** [comment]
What is the latest status on this?

**Comment by oPiZiL** [comment]
@vladimiroltean  I changed the root  directory and  the problem is gone
